// Build-time generator for two dynamic pages on the docs site:
//
//   - `docs/snapshots.md` — a live table of every parsed
//     (spec, edition, sha, fetched_at) snapshot, read straight from
//     `build/spec-*.json` pin headers. The published site rebuilds
//     whenever `refresh.yml` bumps the version (because `package.json`
//     is in `docs.yml`'s paths filter), so the table on the site
//     always matches the currently-published parsed JSONs.
//
//   - `docs/changelog.md` — a verbatim copy of the repo-root
//     `CHANGELOG.md` so VitePress can render it as a page. We copy
//     rather than symlink because symlinks misbehave on Windows
//     clones and across some CI cache layers.
//
// Both outputs are gitignored — they're build artifacts, regenerated
// every time `npm run docs:dev` / `npm run docs:build` runs. If the
// `build/` directory hasn't been populated yet (fresh clone, no
// `npm run parse` yet), the snapshots page renders a placeholder
// telling the reader how to populate it; the docs site never breaks
// on a clean checkout.
//
// Run directly:
//   tsx src/docs/build_data.ts
// or via `npm run docs:data`.

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildToolsPage } from "./build_api_reference.js";

export interface SnapshotRow {
  spec: string;
  edition: string;
  sha: string;
  /** First 8 chars of `sha`, for compact display. */
  short_sha: string;
  fetched_at: string;
  bytes: number;
}

/** Scan `buildDir` for `spec-<spec>-<edition>.json` files and pull
 *  the `pin` header out of each. Cheap: each file is a few MB and
 *  there are at most ~15 of them, so a JSON.parse pass per file is
 *  fine for build-time work. */
export function readSnapshots(buildDir: string): SnapshotRow[] {
  if (!existsSync(buildDir)) return [];
  const files = readdirSync(buildDir).filter((f) =>
    /^spec-(262|402)-.+\.json$/.test(f)
  );
  const rows: SnapshotRow[] = [];
  for (const f of files) {
    const path = join(buildDir, f);
    try {
      const bytes = statSync(path).size;
      const parsed = JSON.parse(readFileSync(path, "utf8")) as {
        pin?: {
          spec?: string;
          edition?: string;
          sha?: string;
          fetched_at?: string;
        };
      };
      const pin = parsed.pin;
      if (!pin || !pin.spec || !pin.edition || !pin.sha) continue;
      rows.push({
        spec: pin.spec,
        edition: pin.edition,
        sha: pin.sha,
        short_sha: pin.sha.slice(0, 8),
        fetched_at: pin.fetched_at ?? "—",
        bytes,
      });
    } catch {
      // Skip any unreadable / malformed file rather than failing the
      // whole docs build. The hosted site rebuilds cheaply; a single
      // bad file shouldn't take it down.
    }
  }
  return sortSnapshots(rows);
}

/** Stable ordering: 262 before 402, then concrete editions ascending
 *  (es2016 → es2026), `main` always last per spec. Keeps the table
 *  predictable. */
function sortSnapshots(rows: SnapshotRow[]): SnapshotRow[] {
  return rows.slice().sort((a, b) => {
    if (a.spec !== b.spec) return a.spec < b.spec ? -1 : 1;
    const aMain = a.edition === "main";
    const bMain = b.edition === "main";
    if (aMain && !bMain) return 1;
    if (!aMain && bMain) return -1;
    if (a.edition < b.edition) return -1;
    if (a.edition > b.edition) return 1;
    return 0;
  });
}

function fmtBytes(b: number): string {
  if (b >= 1024 * 1024) return `${(b / 1024 / 1024).toFixed(1)} MB`;
  if (b >= 1024) return `${(b / 1024).toFixed(0)} KB`;
  return `${b} B`;
}

const PLACEHOLDER_PAGE = `# Snapshots

This page is auto-generated from the local \`build/\` directory.

::: warning Snapshot data not built yet
Run \`npm run fetch-spec && npm run parse\` to populate \`build/\`, then
re-run \`npm run docs:dev\` (or \`npm run docs:build\`). The published
site is generated by CI, which always populates this page from a fresh
parse.
:::

In the published site this page lists every (spec, edition, SHA,
fetched-at) tuple that the running server can serve. The same data is
queryable at runtime via [\`spec.about\`](/tools#specabout) and
[\`spec.snapshots\`](/tools#specsnapshots).
`;

/** Render the snapshots page from a row list. Pure: same input ⇒
 *  same output, so the test below pins the exact format. */
export function renderSnapshotsPage(rows: SnapshotRow[]): string {
  if (rows.length === 0) return PLACEHOLDER_PAGE;

  const total = rows.length;
  const totalBytes = rows.reduce((acc, r) => acc + r.bytes, 0);
  let md = `# Snapshots

This server has parsed and cached **${total}** SHA-pinned snapshots across
ECMA-262 and ECMA-402, totaling ${fmtBytes(totalBytes)} on disk. Every clause
served carries its (spec, edition, SHA, fetched-at) provenance.

The same data is queryable at runtime via [\`spec.about\`](/tools#specabout)
and [\`spec.snapshots\`](/tools#specsnapshots). The hosted Cloudflare Worker
additionally accepts \`at:\` to address historical SHAs — see
[Deployment](/deployment).

## Pinned editions

| Spec | Edition | SHA | Fetched at | Size on disk |
|---|---|---|---|---|
`;
  for (const row of rows) {
    const shaCell = `[\`${row.short_sha}\`](https://github.com/tc39/ecma${row.spec}/commit/${row.sha})`;
    md += `| ${row.spec} | \`${row.edition}\` | ${shaCell} | ${row.fetched_at} | ${fmtBytes(row.bytes)} |\n`;
  }
  md += `
## How this stays current

A scheduled CI workflow checks upstream \`tc39/ecma262\` and
\`tc39/ecma402\` mains every 4 hours. When anything moved, it bumps the
PATCH version of \`tc39-mcp\` and republishes. Because \`package.json\` is
in the docs workflow's paths filter, **this page rebuilds along with
every refresh** — end-to-end latency from upstream merge to updated SHAs
above is typically under 10 minutes.

See [Deployment / Auto-refresh](/deployment) for the full chain.
`;
  return md;
}

/** Rewrite relative Markdown links (`](CONTRIBUTING.md)`) so they
 *  resolve against the GitHub repo when rendered as a docs page —
 *  the docs site doesn't have a `CONTRIBUTING.md` route, but
 *  `https://github.com/xyzzylabs/tc39-mcp/blob/main/CONTRIBUTING.md`
 *  is always the right destination. Skips absolute URLs, fragment
 *  anchors, and links already pointing inside `/docs/`. */
export function rewriteRelativeLinks(md: string): string {
  return md.replace(
    /\]\(((?!https?:\/\/|#|\/|mailto:)[^)\s]+)\)/g,
    "](https://github.com/xyzzylabs/tc39-mcp/blob/main/$1)",
  );
}

/** Copy the repo-root CHANGELOG.md into docs/ so VitePress can route
 *  it as a page. Returns whether the copy happened. */
export function copyChangelog(rootDir: string, docsDir: string): boolean {
  const src = join(rootDir, "CHANGELOG.md");
  const dst = join(docsDir, "changelog.md");
  if (!existsSync(src)) return false;
  const body = readFileSync(src, "utf8");
  writeFileSync(dst, rewriteRelativeLinks(body), "utf8");
  return true;
}

/** Drive the docs outputs from one entrypoint. The script's CLI block
 *  below calls this with `process.cwd()`. */
export function buildDocsData(rootDir: string): void {
  const buildDir = join(rootDir, "build");
  const docsDir = join(rootDir, "docs");
  const rows = readSnapshots(buildDir);
  writeFileSync(join(docsDir, "snapshots.md"), renderSnapshotsPage(rows), "utf8");
  copyChangelog(rootDir, docsDir);
  // Auto-generated tool reference (replaces what used to be hand-written).
  buildToolsPage(rootDir);
}

// CLI: run when invoked directly via `tsx`.
if (import.meta.url === `file://${process.argv[1]}`) {
  buildDocsData(process.cwd());
}
